project:
  type: book
  output-dir: docs

book:
  title: "NLP Song Lyrics"
  author: "Hannah Luebbering"
  date: "6/14/2023"
  chapters:
    - index.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

