project:
  type: book
  #type: website
  output-dir: docs

toc: true
toc-location: right
number-sections: false
bibliography: assets/references.bib

execute:
  enabled: true

book:
  title: "NLP Song Lyrics"
  author: "Hannah Luebbering"
  date: "8/10/2023"
  chapters:
    - index.ipynb
    - 01_sentiment_analysis/01_data.ipynb
    - 01_sentiment_analysis/02_lyrics.ipynb

website:
  navbar:
    logo: assets/images/brand_dist.png
    title: "NLP Song Lyrics"
    background: primary
    pinned: true
    right:
      - href: index.ipynb
        text: Home
      - 01_sentiment_analysis/01_data.ipynb

format:
  html:
    # code-fold: show
    highlight-style: assets/syntax/custom.theme
    syntax-definitions:
      - assets/syntax/python.xml
    theme: cosmo
    css: assets/css/styles.css

editor: visual
# https://www.tensorflow.org/install
# https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment?text=I+like+you.+I+love+you
# https://aeturrell.github.io/coding-for-economists/vis-common-plots.html

