---
title: "Applied Data Mining and Statistical Learning"
subtitle: "Spotify Analysis" 
author: "Hannah Luebbering"

output: 
  html_document: 
    css: "assets/styles.css"
    toc: yes
    toc_float: yes
# knit: pagedown::chrome_print
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
#bibliography: assets/references.bib
#nocite: '@*'
#csl: assets/advanced-optical-materials.csl
---


```{r eval=FALSE, include=FALSE}
library(reticulate)
install_python()
conda_create(
  envname = "reptilia",
  packages = c("pandas", "pyarrow")
)

#conda_list()
#install_miniconda(force = TRUE)

#use_miniconda("reptilia")
```


---------------------------------------


## Applied Data Mining and Statistical Learning


Lesson 1 (b): Exploratory Data Analysis (EDA)
Lesson 2: Statistical Learning and Model Selection
Lesson 3 : Linear Regression
Lesson 4: Variable Selection
Lesson 5: Regression Shrinkage Methods
Lesson 6: Principal Components Analysis
Lesson 7: Dimension Reduction Methods
Lesson 8: Modeling Non-linear Relationships
Lesson 9: Classification
Lesson 10: Support Vector Machines
Lesson 11: Tree-based Methods
Lesson 12: Cluster Analysis


### Understanding + classifying genres using Spotify audio features


- [ ] https://www.kaylinpavlik.com/classifying-songs-genres/



```{r}
library(devtools)
library(tidyverse)
library(knitr)
library(ggjoy)
library(genius)
library(tidytext)
library(textdata)
library(kableExtra)
#devtools::install_github('charlie86/spotifyr')
library(spotifyr)

Sys.setenv(SPOTIFY_CLIENT_ID = '3899576b5fcb4c458beba2cce99aa1b6')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '4f57df7614df4f75b54364bf3c3018fd')

access_token <- get_spotify_access_token()
```




---------------------------------------


## https://rpubs.com/abigail171/taylor


```{r}
taylor <- get_artist_audio_features('taylor swift')
colnames(taylor)
dplyr::select(taylor, c("track_id"))

# py_taylor <- r_to_py(taylor)
```





```{r}
taylor %>% 
  group_by(album_name) %>% 
  select(album_name, duration_ms) %>% 
  summarise(length1=mean(duration_ms)) %>% 
  mutate(length2=length1/1000) %>% 
  mutate(length=length2/60)%>% 
  select(length, album_name) %>% 
  arrange(desc(-length)) -> taylor_mean_length
```


```{r}
taylor <- get_artist_audio_features('taylor swift') %>% 
  filter(album_id == "1NAmidJlEaVgA3MpcPFYGq" | album_id == "5eyZZoQEFQWRHkV2xgAeBw" | album_id == "43OpbkiiIxJO8ktIB777Nn" |
           album_id == "5MfAxS5zz8MlfROjGQVXhy" | album_id == "1EoDsNmgTLtmwe1BDAVxV5" |
           album_id == "2QJmrSgbdM35R67eoGQo4j" | album_id == "6DEjYFkNZh67HP7R9PSZvv")
```



```{r}
taylor %>% 
  group_by(album_name) %>% 
  select(album_name, duration_ms) %>% 
  summarise(length1=mean(duration_ms)) %>% 
  mutate(length2=length1/1000) %>% 
  mutate(length=length2/60)%>% 
  select(length, album_name) %>% 
  arrange(desc(-length)) -> taylor_mean_length

#sort the albums by release date
x1 <- c("Fearless Platinum Edition", "Speak Now",
       "Red", "1989", "reputation", "Lover")
rank <- data.frame("rank" = 1:6)


```



```{r}
taylor_mean_length %>%
  slice(match(x1, album_name)) -> tml_sorted

cbind(tml_sorted, rank) -> tml_sorted2
tml_sorted2
```




```{r}
tml_sorted2 %>%
  ggplot(aes(reorder(album_name, rank), y= length, fill= album_name)) +
  geom_col() +
  coord_flip() +
  scale_fill_manual(values = c("violetred1", "lightsteelblue1", "maroon", "violetred3", "mediumvioletred", "lightsteelblue2", "lightsteelblue3")) + theme_joy() +
  theme(legend.position="none") + ylab("Average Length of Songs") +
  theme(axis.title.y = element_blank())

taylor_mean_length %>% 
  select(album_name, length) %>% 
  kable()
```


```{r}
taylor %>% 
  group_by(album_name, album_release_year) %>% 
  select(album_name, album_release_year, key_name) %>%
  count(key_name) ->taylor_keys


ggplot(taylor_keys, aes(key_name, fill=reorder(album_name, album_release_year), y = n))+
  geom_bar( stat = "identity")+  theme_joy()+
  scale_fill_manual(values=c("lightsteelblue1", "lightsteelblue2", "lightsteelblue3", "maroon", "violetred3", "mediumvioletred","violetred1")) +
  xlab("Key") + ylab("Count") +
  theme(legend.title = element_blank(), axis.title.x = element_text(family = ))
```



```{r}
ggplot(taylor, aes(x= danceability, y= album_name, fill = ..x..)) +
  geom_joy_gradient(scale = 1)+
  scale_fill_gradient(low = "white", high = "violetred1") +
  theme_joy() +
  theme(legend.position="none") +
  xlim(0, 1) +
  xlab("Danceability") + theme(axis.title.y = element_blank())
```



```{r}
taylor %>% 
  group_by(album_name) %>% 
  select(album_name, danceability) %>% 
  summarise(DanceAbility=mean(danceability)) %>% 
  arrange(desc(DanceAbility)) %>% 
  kable() %>% 
  kable_styling(full_width= T, position = "center") 
```








```{r}
taylor_country_genius <- tribble(
  ~artist, ~album,
  "Taylor Swift", "Taylor Swift",
  "Taylor Swift", "Speak Now",
  "Taylor Swift", "Fearless"
) %>%
  add_genius(artist=artist, title=album,type = "album")

```
```{r}
taylor_country_genius %>% 
  unnest_tokens(word, lyric) %>% 
  anti_join(stop_words) -> taylor_country_words
```



```{r}
taylor_country_genius %>% 
  unnest_tokens(word, lyric) %>% 
  anti_join(stop_words) -> taylor_country_words

taylor_pop_genius <- tribble(
  ~artist, ~album,
  "Taylor Swift", "Red",
  "Taylor Swift", "1989",
  "Taylor Swift", "reputation",
  "Taylor Swift", "Lover"
) %>%
  add_genius(artist=artist, title=album,type = "album")
taylor_pop_genius %>% 
  unnest_tokens(word, lyric) %>% 
  anti_join(stop_words) -> taylor_pop_words
```




```{r}
taylor_country_words %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = n, y = as.factor(sentiment), fill = sentiment)) + 
  geom_joy(alpha = .5) + xlab("Word Count") +
  ylab("Sentiment") + theme_joy()  + theme(legend.position = "none") +
  scale_fill_manual(values = c("slategray1", "violetred1")) +
  ggtitle("Country Albums")

taylor_pop_words %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(x = n, y = as.factor(sentiment), fill = sentiment)) + 
  geom_joy(alpha = .5) + xlab("Word Count") +
  ylab("Sentiment") + theme_joy()  + theme(legend.position = "none") +
  scale_fill_manual(values = c("slategray1", "violetred1"))+
  ggtitle("Pop Albums")
```





---------------------------------------

## https://online.stat.psu.edu/stat857/node/45/




## https://rstudio-pubs-static.s3.amazonaws.com/823517_0feeb65691ac43699766f72304b64e17.html


## https://medium.com/@simranvatsa5/taylor-f656e2a09cc3

